// <auto-generated />
using System;
using Integrirani_Sistemi_Proekt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Integrirani_Sistemi_Proekt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Clothing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountL")
                        .HasColumnType("int");

                    b.Property<int>("AmountM")
                        .HasColumnType("int");

                    b.Property<int>("AmountS")
                        .HasColumnType("int");

                    b.Property<int>("AmountXL")
                        .HasColumnType("int");

                    b.Property<int>("AmountXS")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ShopId");

                    b.ToTable("Clothings");
                });

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClothingPiece")
                        .HasColumnType("int");

                    b.Property<string>("Fabric")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Season")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Tag_Clothing", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("ClothingId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "ClothingId");

                    b.HasIndex("ClothingId");

                    b.ToTable("Tag_Clothings");
                });

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Clothing", b =>
                {
                    b.HasOne("Integrirani_Sistemi_Proekt.Models.Brand", "Brand")
                        .WithMany("Clothings")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Integrirani_Sistemi_Proekt.Models.Shop", "Shop")
                        .WithMany("Clothings")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Tag_Clothing", b =>
                {
                    b.HasOne("Integrirani_Sistemi_Proekt.Models.Clothing", "Clothing")
                        .WithMany("Tag_Clothings")
                        .HasForeignKey("ClothingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Integrirani_Sistemi_Proekt.Models.Tag", "Tag")
                        .WithMany("Tag_Clothings")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothing");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Brand", b =>
                {
                    b.Navigation("Clothings");
                });

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Clothing", b =>
                {
                    b.Navigation("Tag_Clothings");
                });

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Shop", b =>
                {
                    b.Navigation("Clothings");
                });

            modelBuilder.Entity("Integrirani_Sistemi_Proekt.Models.Tag", b =>
                {
                    b.Navigation("Tag_Clothings");
                });
#pragma warning restore 612, 618
        }
    }
}
